# Generated by Django 2.2.9 on 2019-12-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='globant_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
